# Generated by Django 5.0.1 on 2024-01-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
